### ISSUE TITLE
Unable to reproduce results in Table 1

### ISSUE THREAD

**Issue by MubarizZaffar** [nianticlabs/marepo#4]
Hey guys, fantastic work! Very easy to set up the repo too, thanks for open-sourcing as always.

With the released and downloadable models (both ACE and marepo), we should be able to reproduce the results in Table 1 of the paper? I quickly copy your Table below for ease of reference.

![image](https://github.com/nianticlabs/marepo/assets/13636620/6490381d-e4f6-445d-bae2-80f31888ce45)

I am getting a median translation error of 6.66 cm (instead of the 3.9 cm reported in the paper) and a median rotation error of 1.84 degrees on the 7-scenes dataset. I have posted the terminal snapshot below, just to make sure that I am looking at the right printout. I followed all the steps in your readme as-is. I did not modify any of the params in `test_7scenes.sh`
and I am _not_ training/fine-tuning any of the models on my end. Many thanks.

![image](https://github.com/nianticlabs/marepo/assets/13636620/a0cf1312-babf-46fb-a85c-87afedea4142)

**Comment by tcavallari** [comment]
Hi, thank you for reporting the issue.

What you see in the screenshot you attached is the median error for the last sequence of the 7Scenes dataset (Stairs), and it indeed matches the table in the paper.

There was a bug in the public version of the code causing it to not print the average median error across the dataset. That has been fixed in this commit: https://github.com/nianticlabs/marepo/commit/9a45e2bb07e5bb8cb997620088d352b439b13e0e

Can you please pull and retry the evaluation script? It should work correctly now.

**Comment by MubarizZaffar** [comment]
Yeap, it's resolved now. Thanks!
